# Generated by Django 5.2.8 on 2026-01-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('accreditation', models.IntegerField()),
                ('website_valid', models.IntegerField()),
                ('reviews_count', models.IntegerField()),
                ('placement_score', models.IntegerField()),
                ('website', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
