# Generated by Django 5.2.8 on 2026-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='accreditation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='placement_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website_valid',
            field=models.IntegerField(default=0),
        ),
    ]
