# Generated by Django 5.2.8 on 2026-02-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_institution_accreditation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='accreditation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='placement_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='reviews_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website_valid',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institution')),
            ],
        ),
    ]
